server:
  port: 8085
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    # 连接池的配置信息
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springBoot?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: sinopacs
    cluster:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springBoot_test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: sinopacs
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

druid:
  # 连接池的配置信息
  # 初始化大小，最小，最大
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


logging:
  level:
    root: info

mybatis:
  type-aliases-package: com.wry.multi.pojo
  mapper-locations: classpath:mybatis/mapper/*/*.xml




